name: Telegram Bot 24/7

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run Telegram Bot
      timeout-minutes: 4
      run: |
        echo "Starting Telegram Bot..."
        python simple_bot.py &
        BOT_PID=$!
        echo "Bot started with PID: $BOT_PID"
        sleep 240
        echo "Stopping bot for next cycle..."
        kill $BOT_PID 2>/dev/null || true
        echo "Bot cycle completed"