#!/usr/bin/env python3
import requests
import time

# ржЖржкржирж╛рж░ ржмржЯ ржЯрзЛржХрзЗржи  
BOT_TOKEN = '7749655099:AAFuW7m4Vmx3jAbLLqpHfu9-PQ1lj3OUhKw'
API_URL = f"https://api.telegram.org/bot{BOT_TOKEN}"

def send_message(chat_id, text):
    url = f"{API_URL}/sendMessage"
    data = {'chat_id': chat_id, 'text': text, 'parse_mode': 'HTML'}
    
    try:
        response = requests.post(url, data=data, timeout=10)
        return response.json()
    except Exception as e:
        print(f"Error: {e}")
        return None

def get_updates(offset=None):
    url = f"{API_URL}/getUpdates"
    params = {'timeout': 30}
    if offset:
        params['offset'] = offset
    
    try:
        response = requests.get(url, params=params, timeout=35)
        return response.json()
    except Exception as e:
        print(f"Error: {e}")
        return None

def process_message(message):
    chat_id = message['chat']['id']
    user = message['from']
    text = message.get('text', '').strip()
    
    user_id = user['id']
    first_name = user.get('first_name', '')
    last_name = user.get('last_name', '')
    username = user.get('username', 'No username')
    
    if text in ['/start', '/id']:
        response = f"""ЁЯЖФ <b>ржЖржкржирж╛рж░ ржЯрзЗрж▓рж┐ржЧрзНрж░рж╛ржо рждржерзНржп:</b>

ЁЯСд <b>ржирж╛ржо:</b> {first_name} {last_name}
ЁЯФв <b>ржЗржЙржЬрж╛рж░ ржЖржЗржбрж┐:</b> <code>{user_id}</code>
ЁЯСе <b>ржЗржЙржЬрж╛рж░ржирзЗржо:</b> @{username}

тЬЕ <b>ржЖржкржирж╛рж░ ржЗржЙржирж┐ржХ ржЯрзЗрж▓рж┐ржЧрзНрж░рж╛ржо ржЖржЗржбрж┐: {user_id}</b>"""
        
    elif text == '/help':
        response = """ЁЯУ▒ <b>ржЯрзЗрж▓рж┐ржЧрзНрж░рж╛ржо ржЖржЗржбрж┐ ржлрж╛ржЗржирзНржбрж╛рж░ ржмржЯ</b>

<b>ржХржорж╛ржирзНржбрж╕ржорзВрж╣:</b>
/start - ржЖржкржирж╛рж░ ржЯрзЗрж▓рж┐ржЧрзНрж░рж╛ржо ржЖржЗржбрж┐ ржкрж╛ржи
/id - рж╢рзБржзрзБ ржЖржЗржбрж┐ ржиржорзНржмрж░ ржжрзЗржЦрж╛ржи
/help - ржПржЗ рж╕рж╛рж╣рж╛ржпрзНржп ржжрзЗржЦрж╛ржи"""
    
    else:
        response = "рж╣рзНржпрж╛рж▓рзЛ! ЁЯСЛ\n\nржЖржкржирж╛рж░ ржЯрзЗрж▓рж┐ржЧрзНрж░рж╛ржо ржЖржЗржбрж┐ ржкрзЗрждрзЗ /start ржкрж╛ржарж╛ржи!"
    
    send_message(chat_id, response)
    print(f"тЬЕ Response sent to user {user_id} ({first_name})")

def main():
    print("ЁЯдЦ Bot starting...")
    
    # Test connection
    test_url = f"{API_URL}/getMe"
    try:
        response = requests.get(test_url, timeout=10)
        if response.status_code == 200:
            bot_info = response.json()
            if bot_info.get('ok'):
                print(f"тЬЕ Bot connected: @{bot_info['result']['username']}")
            else:
                print("тЭМ Invalid bot token!")
                return
        else:
            print("тЭМ Connection failed!")
            return
    except Exception as e:
        print(f"тЭМ Connection error: {e}")
        return
    
    offset = None
    print("ЁЯЪА Bot is running! Send /start to get your ID")
    
    while True:
        try:
            updates = get_updates(offset)
            
            if updates and updates.get('ok'):
                for update in updates['result']:
                    if 'message' in update:
                        process_message(update['message'])
                    offset = update['update_id'] + 1
            
            time.sleep(1)
            
        except KeyboardInterrupt:
            print("\nЁЯСЛ Bot stopped")
            break
        except Exception as e:
            print(f"тЭМ Error: {e}")
            time.sleep(5)

if name == 'main':
    main()
